#! /bin/bash

# Executes the "gbu" command executable.
#
# Passes all arguments to self to the executable.

# Copyright 2022 Yucheng Liu. GNU GPL3 license.
# GNU GPL3 license copy: https://www.gnu.org/licenses/gpl-3.0.txt

__file=$(realpath ${BASH_SOURCE[0]})
__dir=$(dirname $__file)

$__dir/../exes/gbu.bash "$@"
