#! /bin/bash

# Executes the "gbu" command executable.
#
# Passes all arguments to self to the executable.

# Copyright 2022-2025 Yucheng Liu. Under the GNU AGPL 3.0 license.
# GNU AGPL 3.0 license: https://www.gnu.org/licenses/agpl-3.0.txt .

__file=$(realpath ${BASH_SOURCE[0]})
__dir=$(dirname $__file)

$__dir/../exes/gbu.bash "$@"
